
[author=FullstackS]
company = FullStackS GmbH

[launcher]
author = FullstackS
description = This Add-On takes care that the Exoscale Authentication and Mutation log entries are parsed and converted correctly to the CIM format.
version = 0.0.0

[package]
id = Splunk_TA_Exoscale_fs

[install]
state = enabled
state_change_requires_restart = false


[ui]
is_visible = true
show_in_nav = true
label = Exoscale Technical Add-On for CIM Normalization
