[exoscale_route_auth]
REGEX = \"handler\"\s*:\s*\"(authenticate|create session|revoke session)\"
DEST_KEY = MetaData:Sourcetype
FORMAT = sourcetype::exoscale:audittrail:auth

[exoscale_route_mutation]
REGEX = \"handler\"\s*:\s*\".+\"
DEST_KEY = MetaData:Sourcetype
FORMAT = sourcetype::exoscale:audittrail:mutation
