name: CI/CD

on:
  push:
    branches:
      - main


jobs:
  semver:
    uses: ./.github/workflows/sem_rel.yaml

  build:
    needs: semver
    uses: ./.github/workflows/setup_repository.yaml
    with:
      version: ${{ needs.semver.outputs.version }}
      artifact_addon_name: SA-Exoscale_fs
