name: CI/CD

on:
  push:
    branches:
      - main


jobs:
  semver:
    uses: ./.github/workflows/sem_rel.yaml

  debug:
    needs: semver
    runs-on: ubuntu-latest
    steps:
      - run: echo "VERSION='${{ needs.semver.outputs.version }}'"

  build:
    needs: semver
    uses: ./.github/workflows/setup_repository.yaml
    with:
      version: ${{ needs.semver.outputs.version }}
      artifact_addon_name: SA-Exoscale_fs
