name: PR Preview (artifact)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions: {}

concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  semver:
    permissions:
      contents: read
    uses: FullStackS-GmbH/splunk-workflows/.github/workflows/semver_pr.yaml@v1.5.0
    with:
      pr_number: ${{ github.event.pull_request.number }}
      sha: ${{ github.sha }}

  build:
    needs: semver
    permissions:
      contents: read
    uses: FullStackS-GmbH/splunk-workflows/.github/workflows/build.yaml@v1.5.0
    with:
      version: ${{ needs.semver.outputs.version }}
      artifact_report_name: ${{ vars.REPORT_NAME }}

  pr_artifact_comment:
    needs: [ semver, build ]
    permissions:
      issues: write
    uses: FullStackS-GmbH/splunk-workflows/.github/workflows/pr_artifact_comment.yaml@v1.5.0
    with:
      version: ${{ needs.semver.outputs.version }}
      pr_number: ${{ github.event.pull_request.number }}
      artifact_url: ${{ needs.build.outputs.artifact_url }}
      artifact_digest: ${{ needs.build.outputs.artifact_digest }}
