name: PR Preview (draft release)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions:
  contents: write   # needed to create/update releases
  pull-requests: write

concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  semver:
    uses: FullStackS-GmbH/splunk-workflows/.github/workflows/semver.yaml@v1.1.5
    with:
      mode: pr
      pr_number: ${{ github.event.pull_request.number }}
      sha: ${{ github.sha }}

  build:
    needs: semver
    uses: FullStackS-GmbH/splunk-workflows/.github/workflows/build.yaml@v1.1.5
    with:
      version: ${{ needs.semver.outputs.version }}
      artifact_addon_name: ${{ vars.ADDON_NAME }}
      artifact_report_name: ${{ vars.REPORT_NAME }}

  release:
    needs: [semver, build]
    uses: FullStackS-GmbH/splunk-workflows/.github/workflows/release.yaml@v1.1.5
    with:
      version: ${{ needs.semver.outputs.version }}
      draft: true
      prerelease: true
      # optional but recommended so each PR has a stable tag:
      tag: pr-${{ github.event.pull_request.number }}
      target_commitish: ${{ github.sha }}
      mode: pr

  pr_release_comment:
    needs: [ semver, build, release ]
    uses: FullStackS-GmbH/splunk-workflows/.github/workflows/pr_release_comment.yaml@v1.1.5
    with:
      tag: pr-${{ github.event.pull_request.number }}
      version: ${{ needs.semver.outputs.version }}
      pr_number: ${{ github.event.pull_request.number }}
      url: ${{ needs.release.outputs.url }}
