name: Python UV - Lint & Tests

on:
  workflow_call:
    inputs:
      uv_version:
        type: string
        default: "0.10.2"
      version:
        type: string
        required: true
      artifact_addon_name:
        type: string
        default: "ucc-addon"
      artifact_report_name:
        type: string
        default: "splunk-validation-report"

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ inputs.uv_version }}
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Lint
        run: uv run ruff check .

      - name: Build Add-on
        run: |
          mkdir -p dist
          uv run ucc-gen build --source "${{ inputs.artifact_addon_name}}/package" --ta-version "${{inputs.version }}" -o dist

      - name: Validate the Add-on
        run: |
          uv run ucc-gen validate --addon-path dist/"${{ inputs.artifact_addon_name}}" | tee appinspect.txt

      - name: Clean up of appinspect
        run: |
          awk -v app="${{ inputs.artifact_addon_name}}" '
              $0 ~ app " Report Summary:" {found=1}
              found
          ' "appinspect.txt" > "appinspect.txt"

      - name: Package the Add-on
        run: |
          uv run ucc-gen package --path dist/"${{ inputs.artifact_addon_name}}" -o output

      - name: Upload built add-on
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_addon_name }}
          path: output/*

      - name: Upload validation report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_report_name }}
          path: appinspect.txt
